package fr.devnewton.hoerbertgui;

import fr.devnewton.hoerbertgui.io.HoerbertIO;
import java.awt.CardLayout;
import java.io.File;

public class HoerbertApp extends javax.swing.JFrame {

    /**
     * Creates new form HoerbertguiMain
     */
    public HoerbertApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        buttonsPanel = new javax.swing.JPanel();
        violetButton = new javax.swing.JButton();
        rougeButton = new javax.swing.JButton();
        bleuFonceButton = new javax.swing.JButton();
        vertClairButton = new javax.swing.JButton();
        jauneButton = new javax.swing.JButton();
        turquoiseButton = new javax.swing.JButton();
        bleuClairButton = new javax.swing.JButton();
        orangeButton = new javax.swing.JButton();
        vertFonceButton = new javax.swing.JButton();
        violetPlaylist = new fr.devnewton.hoerbertgui.PlaylistPanel();
        rougePlaylist = new fr.devnewton.hoerbertgui.PlaylistPanel();
        bleuFoncePlaylist = new fr.devnewton.hoerbertgui.PlaylistPanel();
        vertClairPlaylist = new fr.devnewton.hoerbertgui.PlaylistPanel();
        jaunePlaylist = new fr.devnewton.hoerbertgui.PlaylistPanel();
        turquoisePlaylist = new fr.devnewton.hoerbertgui.PlaylistPanel();
        bleuClairPlaylist = new fr.devnewton.hoerbertgui.PlaylistPanel();
        orangePlaylist = new fr.devnewton.hoerbertgui.PlaylistPanel();
        vertFoncePlaylist = new fr.devnewton.hoerbertgui.PlaylistPanel();
        statusPanel = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        mainPanel.setLayout(new java.awt.CardLayout());

        buttonsPanel.setLayout(new java.awt.GridLayout(3, 3));

        violetButton.setBackground(new java.awt.Color(120, 88, 155));
        violetButton.setText("Violet");
        violetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                violetButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(violetButton);

        rougeButton.setBackground(new java.awt.Color(194, 14, 26));
        rougeButton.setText("Rouge");
        rougeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rougeButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(rougeButton);

        bleuFonceButton.setBackground(new java.awt.Color(48, 56, 128));
        bleuFonceButton.setText("Bleu foncé");
        bleuFonceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bleuFonceButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(bleuFonceButton);

        vertClairButton.setBackground(new java.awt.Color(161, 192, 55));
        vertClairButton.setText("Vert clair");
        vertClairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vertClairButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(vertClairButton);

        jauneButton.setBackground(new java.awt.Color(242, 204, 19));
        jauneButton.setText("Jaune");
        jauneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jauneButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(jauneButton);

        turquoiseButton.setBackground(new java.awt.Color(141, 167, 204));
        turquoiseButton.setText("Turquoise");
        turquoiseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turquoiseButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(turquoiseButton);

        bleuClairButton.setBackground(new java.awt.Color(0, 157, 224));
        bleuClairButton.setText("Bleu clair");
        bleuClairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bleuClairButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(bleuClairButton);

        orangeButton.setBackground(new java.awt.Color(226, 150, 66));
        orangeButton.setText("Orange");
        orangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orangeButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(orangeButton);

        vertFonceButton.setBackground(new java.awt.Color(40, 119, 62));
        vertFonceButton.setText("Vert foncé");
        vertFonceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vertFonceButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(vertFonceButton);

        mainPanel.add(buttonsPanel, "buttons");

        violetPlaylist.setBackground(new java.awt.Color(120, 88, 155));
        violetPlaylist.setName(""); // NOI18N
        mainPanel.add(violetPlaylist, "violet");

        rougePlaylist.setBackground(new java.awt.Color(194, 14, 26));
        rougePlaylist.setName(""); // NOI18N
        mainPanel.add(rougePlaylist, "rouge");

        bleuFoncePlaylist.setBackground(new java.awt.Color(48, 56, 128));
        bleuFoncePlaylist.setName(""); // NOI18N
        mainPanel.add(bleuFoncePlaylist, "bleuFonce");

        vertClairPlaylist.setBackground(new java.awt.Color(161, 192, 55));
        vertClairPlaylist.setName(""); // NOI18N
        mainPanel.add(vertClairPlaylist, "vertClair");

        jaunePlaylist.setBackground(new java.awt.Color(242, 204, 19));
        jaunePlaylist.setName(""); // NOI18N
        mainPanel.add(jaunePlaylist, "jaune");

        turquoisePlaylist.setBackground(new java.awt.Color(141, 167, 204));
        turquoisePlaylist.setName(""); // NOI18N
        mainPanel.add(turquoisePlaylist, "turquoise");

        bleuClairPlaylist.setBackground(new java.awt.Color(0, 157, 224));
        bleuClairPlaylist.setName(""); // NOI18N
        mainPanel.add(bleuClairPlaylist, "bleuClair");

        orangePlaylist.setBackground(new java.awt.Color(226, 150, 66));
        orangePlaylist.setName(""); // NOI18N
        mainPanel.add(orangePlaylist, "orange");

        vertFoncePlaylist.setBackground(new java.awt.Color(40, 119, 62));
        vertFoncePlaylist.setName(""); // NOI18N
        mainPanel.add(vertFoncePlaylist, "vertFonce");

        getContentPane().add(mainPanel);

        statusPanel.setMaximumSize(new java.awt.Dimension(32767, 0));

        statusLabel.setText("Hello");

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(statusPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(statusLabel)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(statusPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(statusLabel)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(statusPanel);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        saveAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rougeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rougeButtonActionPerformed
        showInMainPanel("rouge");
    }//GEN-LAST:event_rougeButtonActionPerformed

    private void violetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_violetButtonActionPerformed
        showInMainPanel("violet");
    }//GEN-LAST:event_violetButtonActionPerformed

    private void bleuFonceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bleuFonceButtonActionPerformed
        showInMainPanel("bleuFonce");
    }//GEN-LAST:event_bleuFonceButtonActionPerformed

    private void vertClairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vertClairButtonActionPerformed
        showInMainPanel("vertClair");
    }//GEN-LAST:event_vertClairButtonActionPerformed

    private void jauneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jauneButtonActionPerformed
        showInMainPanel("jaune");
    }//GEN-LAST:event_jauneButtonActionPerformed

    private void turquoiseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turquoiseButtonActionPerformed
        showInMainPanel("turquoise");
    }//GEN-LAST:event_turquoiseButtonActionPerformed

    private void bleuClairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bleuClairButtonActionPerformed
        showInMainPanel("bleuClair");
    }//GEN-LAST:event_bleuClairButtonActionPerformed

    private void orangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orangeButtonActionPerformed
        showInMainPanel("orange");
    }//GEN-LAST:event_orangeButtonActionPerformed

    private void vertFonceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vertFonceButtonActionPerformed
        showInMainPanel("vertFonce");
    }//GEN-LAST:event_vertFonceButtonActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void saveAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItemActionPerformed
        File[][] playlists = new File[][] {
            this.violetPlaylist.getPlaylist(),
            this.rougePlaylist.getPlaylist(),
            this.bleuFoncePlaylist.getPlaylist(),
            this.vertClairPlaylist.getPlaylist(),
            this.jaunePlaylist.getPlaylist(),
            this.turquoisePlaylist.getPlaylist(),
            this.bleuClairPlaylist.getPlaylist(),
            this.orangePlaylist.getPlaylist(),
            this.vertFoncePlaylist.getPlaylist()
        };
       HoerbertIO.write(playlists, new File("c:\\tmp\\out"));
    }//GEN-LAST:event_saveAsMenuItemActionPerformed

    public void showInMainPanel(String cardName) {
        CardLayout layout = (CardLayout) this.mainPanel.getLayout();
        layout.show(this.mainPanel, cardName);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoerbertApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoerbertApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoerbertApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoerbertApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoerbertApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton bleuClairButton;
    private fr.devnewton.hoerbertgui.PlaylistPanel bleuClairPlaylist;
    private javax.swing.JButton bleuFonceButton;
    private fr.devnewton.hoerbertgui.PlaylistPanel bleuFoncePlaylist;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jauneButton;
    private fr.devnewton.hoerbertgui.PlaylistPanel jaunePlaylist;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton orangeButton;
    private fr.devnewton.hoerbertgui.PlaylistPanel orangePlaylist;
    private javax.swing.JButton rougeButton;
    private fr.devnewton.hoerbertgui.PlaylistPanel rougePlaylist;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JButton turquoiseButton;
    private fr.devnewton.hoerbertgui.PlaylistPanel turquoisePlaylist;
    private javax.swing.JButton vertClairButton;
    private fr.devnewton.hoerbertgui.PlaylistPanel vertClairPlaylist;
    private javax.swing.JButton vertFonceButton;
    private fr.devnewton.hoerbertgui.PlaylistPanel vertFoncePlaylist;
    private javax.swing.JButton violetButton;
    private fr.devnewton.hoerbertgui.PlaylistPanel violetPlaylist;
    // End of variables declaration//GEN-END:variables

}
